### ISSUE TITLE
Coverage of tests?

### ISSUE THREAD

**Issue by TomWagg** [ilikecubesnstuff/commensurability#27]
Have you tested the coverage of your test suite at all?

Tools like [coverage.py](https://coverage.readthedocs.io/en/7.6.1/index.html) can tell you what fraction of the code is actually covered by the tests to ensure you're not missing something. You can also set this up as part of the GitHub workflow when you do the tests.

— https://github.com/openjournals/joss-reviews/issues/7009

**Comment by ilikecubesnstuff** [comment]
Thank you for the suggestion! The code coverage for this package should now be available on [Coveralls](https://coveralls.io/github/ilikecubesnstuff/commensurability) here: https://coveralls.io/github/ilikecubesnstuff/commensurability

There are a few parts of the code I am unsure how to cover with tests, and have chosen to ignore in the coverage reports:
1. matplotlib code (particularly the interactive plots with keyboard/mouse inputs).
2. code specific to supported backends (like `agama`/`gala`/`galpy`).

Otherwise, the current code coverage is ~71%. I will merge #30 after writing a few more tests to improve the coverage.

**Comment by TomWagg** [comment]
Great! Yeah testing plotting and dependency code can be tricky. In some cases it may be appropriate to exclude some of the code from the coverage test: https://coverage.readthedocs.io/en/7.6.4/excluding.html

**Comment by ilikecubesnstuff** [comment]
Code coverage has been improved to 91%.
