### ISSUE TITLE
using_gala examples

### ISSUE THREAD

**Issue by michael-petersen** [ilikecubesnstuff/commensurability#5]
I think these aren't supported right now (totally fine!), but I found the following behaviour:

```
 using_gala % python3.10 random_mw_orbit.py
Traceback (most recent call last):
  File "using_gala/random_mw_orbit.py", line 20, in <module>
    tess = Tessellation.from_gala_orbit(orbit)
AttributeError: 'function' object has no attribute 'from_gala_orbit'
```

Perhaps easiest to drop `gala` support for now?

**Comment by ilikecubesnstuff** [comment]
This example is fixed now - the `Tessellation` class should automatically detect the parent package from the `orbit` object and extract the data accordingly.
```py
tess = Tessellation(orbit, ("x", "y", "z"))
```

Currently, none of the other `galpy` examples have been re-implemented under `gala` examples because the implementations aren't complete in the orbit integration backends (in [`pidgey`](https://github.com/ilikecubesnstuff/pidgey)).

**Comment by ilikecubesnstuff** [comment]
After `pidgey` version 1.0, the `gala` backend accepts Hamiltonian objects as "potentials" that include pattern speed information. The example in this repository has been updated to reflect this change.
